name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      # fix for forcing git to use https when pulling deps
      - run: 'git config --global --replace-all url."https://github.com/".insteadOf ssh://git@github.com/'
      - run: npm ci
      - run: npm run build --if-present
      - name: Run BundleMon
        run: npm run bundlemon
        env:
          BUNDLEMON_PROJECT_ID: 62325f451d1b50bea48f41fb
          CI_COMMIT_SHA: ${{github.event.pull_request.head.sha || github.sha}} # important!
      # Keeping in case we ever want to save build artifacts
      # - name: Zip artifact
      #   run: zip build-artifact -r ./build ./node_modules
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: build-artifact
      #     path: ./build-artifact.zip
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      # fix for forcing git to use https when pulling deps
      - run: 'git config --global --replace-all url."https://github.com/".insteadOf ssh://git@github.com/'
      - run: npm ci
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      # fix for forcing git to use https when pulling deps
      - run: 'git config --global --replace-all url."https://github.com/".insteadOf ssh://git@github.com/'
      - run: npm ci
      - run: npm test
        env:
          CI: true
  
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      # fix for forcing git to use https when pulling deps
      - run: 'git config --global --replace-all url."https://github.com/".insteadOf ssh://git@github.com/'
      - run: npm ci
      - run: npm test -- --coverage
        env:
          CI: true
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  coverage-cypress-stateless:
    runs-on: ubuntu-latest
    services:
      saddle-contract:
        image: saddlefinance/contracts:latest
        ports:
          - 8545:8545
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
          
      - name: 'UI Tests - Stateless'
        uses: cypress-io/github-action@v2
        with: 
          install: true
          start: npm run cy:coveragestateless
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          browser: chrome
          spec: cypress/integration/stateless/*
      - run: npx nyc report --reporter=text
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: E2E Failures
          path: |
            cypress/screenshots/
            cypress/videos/
    env:
      REACT_APP_NOTIFY_DAPP_ID: ${{ secrets.REACT_APP_NOTIFY_DAPP_ID }}

  coverage-cypress-stateful:
    env:
      REACT_APP_NOTIFY_DAPP_ID: ${{ secrets.REACT_APP_NOTIFY_DAPP_ID }}
    runs-on: ubuntu-latest
    services:
      saddle-contract:
        image: saddlefinance/contracts:latest
        ports:
          - 8545:8545
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      # fix for forcing git to use https when pulling deps
      - run: 'git config --global --replace-all url."https://github.com/".insteadOf ssh://git@github.com/'
      - run: npm ci
      - run: npm run cy:coveragestateful
        env:
          CHOKIDAR_USEPOLLING: 1
      - run: npx nyc report --reporter=text
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: E2E Failures
          path: |
            cypress/screenshots/
            cypress/videos/